<?php
add_action( 'acf/include_fields', function() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( array(
	'key' => 'group_6541c3501dcb2',
	'title' => 'Detalles del Cliente API Salesforce',
	'fields' => array(
		array(
			'key' => 'field_6541c814a500d',
			'label' => 'URL endpoint',
			'name' => 'sfclient_url_endpoint',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_654c2e20a6d06',
			'label' => 'Salesforce Account Id',
			'name' => 'sfclient_account_id',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6541ce1a2011e',
			'label' => 'Mapeo de campos API',
			'name' => 'mapeo_de_campos_api',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'table',
			'pagination' => 0,
			'min' => 0,
			'max' => 0,
			'collapsed' => '',
			'button_label' => 'Mapear Nuevo Campo',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_6541ce4a2011f',
					'label' => 'Campo API Cliente',
					'name' => 'campo_api_cliente',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_6541ce1a2011e',
				),
				array(
					'key' => 'field_6541ce7520120',
					'label' => 'Campo API Salesforce',
					'name' => 'campo_api_salesforce',
					'aria-label' => '',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'Id' => 'Id',
						'CaseNumber' => 'CaseNumber',
						'FirstName__c' => 'FirstName__c',
						'Last_Name__c' => 'Last_Name__c',
						'Phone_Numbercontact__c' => 'Phone_Numbercontact__c',
						'Address_Street__c' => 'Address_Street__c',
						'City__c' => 'City__c',
						'StateUS__c' => 'StateUS__c',
						'Area_Code__c' => 'Area_Code__c',
						'Country__c' => 'Country__c',
						'Email__c' => 'Email__c',
						'Date_of_Birth__c' => 'Date_of_Birth__c',
						'Trusted_Form__c' => 'Trusted_Form__c',
						'Status' => 'Status',
						'Type' => 'Type',
						'Diagnosis__c' => 'Diagnosis__c',
						'CLJ_Duration__c' => 'CLJ_Duration__c',
						'CLJ_Work_or_Reside_from_1953_to_1987__c' => 'CLJ_Work_or_Reside_from_1953_to_1987__c',
						'Power_of_Attorney__c' => 'Power_of_Attorney__c',
						'Opportunity_Name__c' => 'Opportunity_Name__c',
						'AccountId__c' => 'AccountId__c',
						'--Otro--' => '--Otro--',
					),
					'default_value' => false,
					'return_format' => 'value',
					'multiple' => 0,
					'allow_null' => 0,
					'ui' => 0,
					'ajax' => 0,
					'placeholder' => '',
					'parent_repeater' => 'field_6541ce1a2011e',
				),
				array(
					'key' => 'field_6541ceba20121',
					'label' => 'Otro',
					'name' => 'otro',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_6541ce1a2011e',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'sfclient',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );
} );